# ===================================================
# 9. í†µí•© ì¸ì¦(Auth) ë°±ì—”ë“œ ë°°í¬
# ===================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-backend-lee-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: auth-backend-lee
  template:
    metadata:
      labels:
        app: auth-backend-lee
    spec:
      nodeSelector:
        agentpool: userpool
      containers:
        - name: auth-backend-lee-container
          # âœ… CI/CD íŒŒì´í”„ë¼ì¸ì— ì˜í•´ ì´ ë³€ìˆ˜ê°€ ì‹¤ì œ ì´ë¯¸ì§€ íƒœê·¸ë¡œ ì¹˜í™˜ë©ë‹ˆë‹¤.
          image: kt16big.azurecr.io/auth-backend-lee:${IMAGE_TAG}
          ports:
            - containerPort: 9001
          env:
            - name: SERVER_PORT    # ğŸ”¥ ì´ê²ƒ ì¶”ê°€!
              value: "9001"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: api-keys-secret
                  key: JWT_SECRET_KEY
            - name: spring.datasource.url
              valueFrom:
                secretKeyRef:
                  name: api-keys-secret
                  key: DB_URL
            - name: spring.datasource.username
              valueFrom:
                secretKeyRef:
                  name: api-keys-secret
                  key: DB_USER
            - name: spring.datasource.password
              valueFrom:
                secretKeyRef:
                  name: api-keys-secret
                  key: DB_PASSWORD
            - name: GMAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: api-keys-secret
                  key: GMAIL_USERNAME
            - name: GMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-keys-secret
                  key: GMAIL_PASSWORD
---
# ===================================================
# 10. í†µí•© ì¸ì¦(Auth) ë°±ì—”ë“œ ì„œë¹„ìŠ¤
# ===================================================
apiVersion: v1
kind: Service
metadata:
  name: auth-backend-lee-service
spec:
  type: ClusterIP
  selector:
    app: auth-backend-lee
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9001